<?php

use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('categories',function(Blueprint $t){$t->id();$t->string('name_bn');$t->string('name_en')->nullable();$t->string('slug')->unique();$t->string('icon',20)->nullable();$t->boolean('is_active')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
Schema::create('subcategories',function(Blueprint $t){$t->id();$t->foreignId('category_id')->constrained()->cascadeOnDelete();$t->string('name_bn');$t->string('name_en')->nullable();$t->string('slug')->unique();$t->string('image_path')->nullable();$t->boolean('is_active')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
Schema::create('products',function(Blueprint $t){$t->id();$t->foreignId('subcategory_id')->nullable()->constrained()->nullOnDelete();$t->string('name_bn');$t->string('name_en')->nullable();$t->string('slug')->unique();$t->string('sku')->unique();$t->decimal('price',12,2);$t->decimal('compare_price',12,2)->nullable();$t->text('short_description')->nullable();$t->longText('description_html')->nullable();$t->unsignedInteger('stock_qty')->default(0);$t->boolean('is_active')->default(true);$t->boolean('is_featured')->default(false);$t->unsignedInteger('sort_order')->default(0);$t->string('meta_title')->nullable();$t->text('meta_description')->nullable();$t->string('main_image_path')->nullable();$t->string('video_path')->nullable();$t->text('video_url')->nullable();$t->timestamps();$t->index(['is_active','is_featured']);});
Schema::create('product_images',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('path');$t->string('alt_text')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
}public function down():void{Schema::dropIfExists('product_images');Schema::dropIfExists('products');Schema::dropIfExists('subcategories');Schema::dropIfExists('categories');}};
