@extends('layouts.store')
@section('title',$product->meta_title ?: ($product->name_bn ?: $product->name_en))
@section('meta_description',$product->meta_description ?: strip_tags($product->short_description ?? ''))
@section('content')
<div class="breadcrumb"><div class="container"><a href="{{ route('home') }}">হোম</a> <span>›</span>@if($product->subcategory)<a href="{{ route('subcategory.show',$product->subcategory->slug) }}">{{ $product->subcategory->name_bn }}</a><span>›</span>@endif {{ $product->name_bn ?: $product->name_en }}</div></div>
<section class="container product-detail"><div class="gallery"><div class="thumbs">@if($product->main_image_path)<button class="thumb active" data-src="{{ asset('storage/'.$product->main_image_path) }}"><img src="{{ asset('storage/'.$product->main_image_path) }}"></button>@endif @foreach($product->images as $img)<button class="thumb" data-src="{{ asset('storage/'.$img->path) }}"><img loading="lazy" src="{{ asset('storage/'.$img->path) }}"></button>@endforeach</div><div class="main-media">@if($product->main_image_path)<img id="mainProductImage" src="{{ asset('storage/'.$product->main_image_path) }}" alt="{{ $product->name_bn ?: $product->name_en }}">@else<div class="image-placeholder">পণ্যের ছবি</div>@endif</div></div>
<div class="product-info"><h1>{{ $product->name_bn ?: $product->name_en }}</h1><div class="stock {{ $product->stock_qty>0?'in':'out' }}">{{ $product->stock_qty>0?'স্টকে আছে':'স্টক শেষ' }}</div><div class="detail-price">৳{{ number_format((float)$product->price,2) }} @if($product->compare_price)<del>৳{{ number_format((float)$product->compare_price,2) }}</del>@endif</div>@if($product->short_description)<div class="short-desc rich-content-short">{!! $product->short_description !!}</div>@endif
<form action="{{ route('cart.add',$product) }}" method="post" id="productOrderForm" class="order-bar track-form quick-order-form product-order-bar" data-meta-event="AddToCart" data-content-id="{{ $product->sku }}" data-value="{{ $product->price }}">@csrf<div class="qty"><button type="button" onclick="stepQty(this,-1)">−</button><input name="quantity" value="1" min="1" max="99" inputmode="numeric"><button type="button" onclick="stepQty(this,1)">+</button></div><button class="btn primary grow" @disabled($product->stock_qty<1)>অর্ডার করুন</button></form>
<div class="trust-line">✓ সহজ অর্ডার &nbsp; ✓ দ্রুত ডেলিভারি &nbsp; ✓ ক্যাশ অন ডেলিভারি</div></div></section>
<div class="mobile-sticky-order" id="mobileStickyOrder" aria-hidden="true">
    <div class="mobile-sticky-price"><small>মূল্য</small><strong>৳{{ number_format((float)$product->price,2) }}</strong></div>
    <button type="button" class="btn primary mobile-sticky-order-button" data-submit-order-form="productOrderForm" @disabled($product->stock_qty<1)>অর্ডার করুন</button>
</div>
<section class="container product-description"><div class="description-tabs"><b>পণ্যের বিবরণ</b></div>@if($product->video_path)<video controls preload="metadata" class="product-video"><source src="{{ asset('storage/'.$product->video_path) }}"></video>@elseif($product->video_url)<div class="video-link"><a class="btn outline" target="_blank" rel="noopener" href="{{ $product->video_url }}">ভিডিও দেখুন</a></div>@endif<div class="rich-content">{!! $product->description_html !!}</div></section>
@if($related->count())<section class="container section"><h2 class="section-title">সম্পর্কিত পণ্য</h2><div class="product-grid">@foreach($related as $item)@include('store.partials.product-card',['product'=>$item])@endforeach</div></section>@endif
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{window.trackMeta?.('ViewContent',{content_ids:[@json($product->sku)],content_type:'product',content_name:@json($product->name_bn ?: $product->name_en),currency:'BDT',value:{{ (float)$product->price }}});document.querySelectorAll('.thumb').forEach(b=>b.addEventListener('click',()=>{const i=document.getElementById('mainProductImage');if(i)i.src=b.dataset.src;document.querySelectorAll('.thumb').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));});</script>@endpush
